In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib notebook
import seaborn as sns

In [2]:
train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv")

In [3]:
train_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
test_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [5]:
train_data.drop(["Alley", "FireplaceQu", "PoolQC", "Fence", "MiscFeature"], axis = 1, inplace = True)
test_data.drop(["Alley", "FireplaceQu", "PoolQC", "Fence", "MiscFeature"], axis = 1, inplace = True)

In [6]:
col = list(train_data.columns)
col.remove("SalePrice")
print(col)

['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SaleType', 'SaleCondition']

In [7]:
non_cat_features = ['LotFrontage', "LotArea", "YearBuilt", "YearRemodAdd", "MasVnrArea", "BsmtFinSF1", "BsmtFinSF2",
                    "BsmtUnfSF", "TotalBsmtSF", "1stFlrSF", "2ndFlrSF", "LowQualFinSF", "GrLivArea", "BsmtFullBath", 
                    "BsmtHalfBath", "FullBath", "HalfBath", "BedroomAbvGr", "KitchenAbvGr", "TotRmsAbvGrd", "Fireplaces", 
                    "GarageYrBlt", "GarageCars", "GarageArea", "WoodDeckSF", "OpenPorchSF", "EnclosedPorch", "3SsnPorch", 
                    "ScreenPorch", "PoolArea", "MiscVal", "MoSold", "YrSold"]

In [8]:
cat_features = col.copy()
# print(cat_features)
for i in non_cat_features:
#     print(i)
    cat_features.remove(i)

In [9]:
print(cat_features)

['Id', 'MSSubClass', 'MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'SaleType', 'SaleCondition']

In [10]:
import category_encoders as ce

In [11]:
target_enc = ce.TargetEncoder(cols = cat_features)
target_enc.fit(train_data[cat_features], train_data["SalePrice"])

TargetEncoder(cols=['Id', 'MSSubClass', 'MSZoning', 'Street', 'LotShape',
                    'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
                    'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
                    'HouseStyle', 'OverallQual', 'OverallCond', 'RoofStyle',
                    'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
                    'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
                    'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
                    'Heating', ...],
              drop_invariant=False, handle_missing='value',
              handle_unknown='value', min_samples_leaf=1, return_df=True,
              smoothing=1.0, verbose=0)

In [12]:
t1 = train_data.copy()
t1[cat_features] = target_enc.transform(train_data[cat_features])
t1.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,180921.19589,239948.501672,191004.994787,65.0,8450,181130.538514,164754.818378,180183.746758,180950.95682,176938.047529,...,0,0,0,0,0,2,2008,173401.836622,175202.219533,208500
1,180921.19589,185224.811567,191004.994787,80.0,9600,181130.538514,164754.818378,180183.746758,180950.95682,177934.574468,...,0,0,0,0,0,5,2007,173401.836622,175202.219533,181500
2,180921.19589,239948.501672,191004.994787,68.0,11250,181130.538514,206101.665289,180183.746758,180950.95682,176938.047529,...,0,0,0,0,0,9,2008,173401.836622,175202.219533,223500
3,180921.19589,166772.416667,191004.994787,60.0,9550,181130.538514,206101.665289,180183.746758,180950.95682,181623.425856,...,272,0,0,0,0,2,2006,173401.836622,146526.623762,140000
4,180921.19589,239948.501672,191004.994787,84.0,14260,181130.538514,206101.665289,180183.746758,180950.95682,177934.574468,...,0,0,0,0,0,12,2008,173401.836622,175202.219533,250000

In [13]:
t1.fillna(t1.mean(), inplace = True)

In [14]:
t2 = test_data.copy()
t2[cat_features] = target_enc.transform(t2[cat_features])
t2.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,180921.19589,185224.811567,131558.390100,80.0,11622,181130.538514,164754.818378,180183.746758,180950.95682,176938.047529,...,0,0,0,120,0,0,6,2010,173401.836622,175202.219533
1,180921.19589,185224.811567,191004.994787,81.0,14267,181130.538514,206101.665289,180183.746758,180950.95682,181623.425856,...,36,0,0,0,0,12500,6,2010,173401.836622,175202.219533
2,180921.19589,239948.501672,191004.994787,74.0,13830,181130.538514,206101.665289,180183.746758,180950.95682,176938.047529,...,34,0,0,0,0,0,3,2010,173401.836622,175202.219533
3,180921.19589,239948.501672,191004.994787,78.0,9978,181130.538514,206101.665289,180183.746758,180950.95682,176938.047529,...,36,0,0,0,0,0,6,2010,173401.836622,175202.219533
4,180921.19589,200779.080460,191004.994787,43.0,5005,181130.538514,206101.665289,231533.940000,180950.95682,176938.047529,...,82,0,0,144,0,0,1,2010,173401.836622,175202.219533

In [15]:
t2.fillna(t2.mean(), inplace = True)

In [16]:
from sklearn.linear_model import LinearRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [17]:
X_train = t1[col]
Y_train = t1["SalePrice"]

In [24]:
scaler = StandardScaler()
x = scaler.fit_transform(X_train.copy())

In [25]:
lr = LinearRegression(normalize = True).fit(x, Y_train)

In [26]:
lr.score(x, Y_train)

0.8719399438694958

In [27]:
gbr = GradientBoostingRegressor().fit(x, Y_train)

In [28]:
gbr.score(x, Y_train)

0.9683117049017608

In [40]:
mlp = MLPRegressor(hidden_layer_sizes = [40, 20, 10, 5], learning_rate_init = 0.1).fit(x, Y_train)

In [41]:
mlp.score(x, Y_train)

0.9649179454823844

In [42]:
x_test = scaler.fit_transform(t2.copy())

In [49]:
pred = gbr.predict(x_test)

In [50]:
Id = np.array(test_data["Id"], dtype = int)

In [51]:
print(len(Id))
print(len(pred))

1459
1459

In [52]:
ans = pd.DataFrame(Id)
ans["SalePrice"] = pred
ans.columns = ["Id", "SalePrice"]
# ans["Id"].apply(lambda x : int(x))
ans.head()

     Id      SalePrice
0  1461  129535.023090
1  1462  161700.301877
2  1463  190908.349193
3  1464  190758.393097
4  1465  207469.192758

In [53]:
ans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 2 columns):
Id           1459 non-null int32
SalePrice    1459 non-null float64
dtypes: float64(1), int32(1)
memory usage: 17.2 KB

In [54]:
ans.to_csv("submission.csv", index = False)